version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Usa.2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    depends_on:
      - postgres_db
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: Usa.2025
      DB_HOST: postgres_db
      DB_PORT: 5432
    ports:
      - "3000:3000"

volumes:
  postgres_data:
